import '../models/handover.dart';
import '../models/handover_status.dart';
import '../models/handover_event.dart';
import '../models/user_profile.dart';

class MockData {
  static const UserProfile defaultUser = UserProfile(
    id: 'user_maya_01',
    fullName: 'Maya Chen',
    email: 'maya@northline.studio',
    organization: 'Northline Studio',
    avatarInitials: 'MC',
    returnRemindersEnabled: true,
  );

  static List<Handover> getInitialHandovers() {
    return [
      Handover(
        id: 'hn_01',
        token: 'HN-1048',
        itemName: 'MacBook Pro 14"',
        category: 'Electronics',
        identifier: 'NL-MBP-014',
        description:
            'Space gray, 14-inch. Includes charger. No visible damage at handover.',
        photoAsset: 'assets/images/item_laptop.png',
        senderName: 'Maya Chen',
        senderOrg: 'Northline Studio',
        receiverName: 'Jordan Lee',
        receiverOrg: 'Northline Studio',
        receiverEmail: 'jordan@northline.studio',
        receiverPhone: '+1 (555) 019-2834',
        returnExpected: true,
        returnDueAt: DateTime(2026, 10, 16, 17, 0),
        receivedAt: DateTime(2026, 10, 14, 9, 12),
        status: HandoverStatus.received,
        notes: 'For the studio workshop. Please return with the charger.',
        events: [
          HandoverEvent(
            id: 'ev_01',
            title: 'Record created by Maya Chen',
            timestamp: DateTime(2026, 10, 14, 9, 0),
            type: HandoverEventType.created,
            performedBy: 'Maya Chen',
          ),
          HandoverEvent(
            id: 'ev_02',
            title: 'Jordan confirmed physical receipt',
            timestamp: DateTime(2026, 10, 14, 9, 12),
            type: HandoverEventType.received,
            performedBy: 'Jordan Lee',
          ),
        ],
      ),
      Handover(
        id: 'hn_02',
        token: 'HN-1049',
        itemName: 'Degree certificate',
        category: 'Documents',
        identifier: 'ED-CH-2024',
        description: 'Original Bachelor Degree Certificate in protective folder.',
        photoAsset: 'assets/images/item_cert.png',
        senderName: 'Maya Chen',
        senderOrg: 'Northline Studio',
        receiverName: 'Eastbridge Admissions',
        receiverOrg: 'Eastbridge Admissions',
        receiverEmail: 'admissions@eastbridge.edu',
        returnExpected: true,
        returnDueAt: DateTime(2026, 10, 21, 12, 0),
        status: HandoverStatus.pending,
        notes: 'Verification intake for graduation archive.',
        events: [
          HandoverEvent(
            id: 'ev_03',
            title: 'Record created by Maya Chen',
            timestamp: DateTime(2026, 10, 14, 8, 30),
            type: HandoverEventType.created,
            performedBy: 'Maya Chen',
          ),
        ],
      ),
      Handover(
        id: 'hn_03',
        token: 'HN-1050',
        itemName: 'Studio keys',
        category: 'Keys & Access',
        identifier: 'KEY-B4-MAIN',
        description: 'Main entrance and workshop master keys on blue fob.',
        photoAsset: 'assets/images/item_keys.png',
        senderName: 'Maya Chen',
        senderOrg: 'Northline Studio',
        receiverName: 'Alex Rivera',
        receiverOrg: 'Sound Design Lab',
        receiverEmail: 'alex@soundlab.design',
        returnExpected: true,
        returnDueAt: DateTime(2026, 10, 12, 18, 0),
        receivedAt: DateTime(2026, 10, 10, 10, 15),
        status: HandoverStatus.overdue,
        notes: 'Overnight access for audio rendering.',
        events: [
          HandoverEvent(
            id: 'ev_04',
            title: 'Record created by Maya Chen',
            timestamp: DateTime(2026, 10, 10, 10, 0),
            type: HandoverEventType.created,
            performedBy: 'Maya Chen',
          ),
          HandoverEvent(
            id: 'ev_05',
            title: 'Alex Rivera confirmed physical receipt',
            timestamp: DateTime(2026, 10, 10, 10, 15),
            type: HandoverEventType.received,
            performedBy: 'Alex Rivera',
          ),
          HandoverEvent(
            id: 'ev_06',
            title: 'Return deadline passed',
            timestamp: DateTime(2026, 10, 12, 18, 0),
            type: HandoverEventType.deadlinePassed,
          ),
        ],
      ),
      Handover(
        id: 'hn_04',
        token: 'HN-1051',
        itemName: 'iPhone 15',
        category: 'Electronics',
        identifier: 'DEV-IP15-02',
        description: 'Testing device, iOS 17.6 installed with test certificates.',
        photoAsset: 'assets/images/item_iphone.png',
        senderName: 'Maya Chen',
        senderOrg: 'Northline Studio',
        receiverName: 'Riley Park',
        receiverOrg: 'QA Core',
        receiverEmail: 'riley@northline.studio',
        returnExpected: true,
        returnDueAt: DateTime(2026, 10, 10, 16, 0),
        receivedAt: DateTime(2026, 10, 8, 14, 0),
        returnedAt: DateTime(2026, 10, 10, 15, 45),
        status: HandoverStatus.returned,
        notes: 'Release regression testing.',
        events: [
          HandoverEvent(
            id: 'ev_07',
            title: 'Record created by Maya Chen',
            timestamp: DateTime(2026, 10, 8, 13, 40),
            type: HandoverEventType.created,
            performedBy: 'Maya Chen',
          ),
          HandoverEvent(
            id: 'ev_08',
            title: 'Riley Park confirmed physical receipt',
            timestamp: DateTime(2026, 10, 8, 14, 0),
            type: HandoverEventType.received,
            performedBy: 'Riley Park',
          ),
          HandoverEvent(
            id: 'ev_09',
            title: 'Maya confirmed physical return',
            timestamp: DateTime(2026, 10, 10, 15, 45),
            type: HandoverEventType.returned,
            performedBy: 'Maya Chen',
          ),
        ],
      ),
      Handover(
        id: 'hn_05',
        token: 'HN-1052',
        itemName: 'Camera kit',
        category: 'Equipment',
        identifier: 'CAM-A7IV-01',
        description: 'Sony A7IV with 24-70mm GM lens and 2 batteries in bag.',
        photoAsset: 'assets/images/item_camera.png',
        senderName: 'Maya Chen',
        senderOrg: 'Northline Studio',
        receiverName: 'Sam Patel',
        receiverOrg: 'Photography Collective',
        receiverEmail: 'sam@collectivestudio.com',
        returnExpected: true,
        returnDueAt: DateTime(2026, 10, 16, 17, 0),
        receivedAt: DateTime(2026, 10, 13, 11, 0),
        status: HandoverStatus.disputed,
        issueReason: 'Item condition differs',
        issueDescription:
            'Small scuff on the laptop lid noticed during return inspection. Charger is present.',
        notes: 'Brand campaign shoot on location.',
        events: [
          HandoverEvent(
            id: 'ev_10',
            title: 'Record created by Maya Chen',
            timestamp: DateTime(2026, 10, 13, 10, 45),
            type: HandoverEventType.created,
            performedBy: 'Maya Chen',
          ),
          HandoverEvent(
            id: 'ev_11',
            title: 'Sam Patel confirmed physical receipt',
            timestamp: DateTime(2026, 10, 13, 11, 0),
            type: HandoverEventType.received,
            performedBy: 'Sam Patel',
          ),
          HandoverEvent(
            id: 'ev_12',
            title: 'Maya recorded a condition issue',
            timestamp: DateTime(2026, 10, 18, 12, 10),
            type: HandoverEventType.issueRecorded,
            performedBy: 'Maya Chen',
            description: 'Item condition differs: small scuff noted.',
          ),
        ],
      ),
      Handover(
        id: 'hn_06',
        token: 'HN-1053',
        itemName: 'Signed contract',
        category: 'Documents',
        identifier: 'CTR-2026-99',
        description: 'Studio lease agreement original executed copy.',
        photoAsset: 'assets/images/item_contract.png',
        senderName: 'Maya Chen',
        senderOrg: 'Northline Studio',
        receiverName: 'Nora Brooks',
        receiverOrg: 'Building Management',
        receiverEmail: 'nora@property.io',
        returnExpected: false,
        status: HandoverStatus.cancelled,
        notes: 'Replaced by electronic signature docu-pack.',
        events: [
          HandoverEvent(
            id: 'ev_13',
            title: 'Record created by Maya Chen',
            timestamp: DateTime(2026, 10, 11, 9, 0),
            type: HandoverEventType.created,
          ),
          HandoverEvent(
            id: 'ev_14',
            title: 'Handover cancelled by sender',
            timestamp: DateTime(2026, 10, 11, 14, 0),
            type: HandoverEventType.cancelled,
          ),
        ],
      ),
      Handover(
        id: 'hn_07',
        token: 'HN-1054',
        itemName: 'Office key',
        category: 'Keys & Access',
        identifier: 'KEY-SUITE-301',
        description: 'Guest RFID card and physical brass key.',
        photoAsset: 'assets/images/item_office_key.png',
        senderName: 'Maya Chen',
        senderOrg: 'Northline Studio',
        receiverName: 'Ellis Morgan',
        receiverOrg: 'Visiting Contractor',
        receiverEmail: 'ellis@contracting.com',
        returnExpected: true,
        returnDueAt: DateTime(2026, 10, 12, 19, 0),
        status: HandoverStatus.expired,
        notes: 'Confirmation code expired before handover completed.',
        events: [
          HandoverEvent(
            id: 'ev_15',
            title: 'Record created by Maya Chen',
            timestamp: DateTime(2026, 10, 11, 8, 30),
            type: HandoverEventType.created,
          ),
          HandoverEvent(
            id: 'ev_16',
            title: 'Confirmation code expired',
            timestamp: DateTime(2026, 10, 12, 9, 0),
            type: HandoverEventType.expired,
          ),
        ],
      ),
    ];
  }

  static List<Handover> getReceivedByMeHandovers() {
    return [
      Handover(
        id: 'hn_rec_01',
        token: 'HN-2091',
        itemName: 'Dell Display 27"',
        category: 'Electronics',
        identifier: 'NL-MON-029',
        description: '4K IPS USB-C Monitor with power cable.',
        photoAsset: 'assets/images/item_laptop.png',
        senderName: 'David Kim',
        senderOrg: 'IT Support',
        receiverName: 'Maya Chen',
        receiverOrg: 'Northline Studio',
        receiverEmail: 'maya@northline.studio',
        returnExpected: true,
        returnDueAt: DateTime(2026, 10, 25, 17, 0),
        receivedAt: DateTime(2026, 10, 12, 14, 30),
        status: HandoverStatus.received,
        events: [
          HandoverEvent(
            id: 'ev_rec_01',
            title: 'David Kim created the record',
            timestamp: DateTime(2026, 10, 12, 14, 0),
            type: HandoverEventType.created,
          ),
          HandoverEvent(
            id: 'ev_rec_02',
            title: 'Maya confirmed physical receipt',
            timestamp: DateTime(2026, 10, 12, 14, 30),
            type: HandoverEventType.received,
          ),
        ],
      ),
    ];
  }
}
